import type { Metadata } from 'next';
import React from 'react';
import { Analytics } from '@vercel/analytics/react';
import EmotionProvider from '@/lib/provider/emotion';
import Header from '@/components/header';
import { GoogleAnalytics, GoogleTagManager } from '@next/third-parties/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
      <body>
        <EmotionProvider>
          <Header />
          <GoogleAnalytics gaId="G-V7EEJ7FY6J" />
          <GoogleTagManager gtmId="GTM-59QSW5L7" />
          {children}
          <Analytics />
        </EmotionProvider>
      </body>
    </html>

  );
}
